//
// HierarchyLimitsMaxUpTransitions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct HierarchyLimitsMaxUpTransitions: Codable, Hashable {
    public var _1: Int? = 400
    public var _2: Int? = 100

    public init(_1: Int? = 400, _2: Int? = 100) {
        self._1 = _1
        self._2 = _2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _1 = "1"
        case _2 = "2"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_1, forKey: ._1)
        try container.encodeIfPresent(_2, forKey: ._2)
    }
}
