//
// HierarchyLimitsExpandWithinDistance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct HierarchyLimitsExpandWithinDistance: Codable, Hashable {
    public var _0: Int? = 100_000_000
    public var _1: Int? = 20000
    public var _2: Int? = 5000

    public init(_0: Int? = 100_000_000, _1: Int? = 20000, _2: Int? = 5000) {
        self._0 = _0
        self._1 = _1
        self._2 = _2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _0 = "0"
        case _1 = "1"
        case _2 = "2"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_0, forKey: ._0)
        try container.encodeIfPresent(_1, forKey: ._1)
        try container.encodeIfPresent(_2, forKey: ._2)
    }
}
