//
// HierarchyLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct HierarchyLimits: Codable, Hashable {
    public var expandWithinDistance: HierarchyLimitsExpandWithinDistance?
    public var maxUpTransitions: HierarchyLimitsMaxUpTransitions?

    public init(expandWithinDistance: HierarchyLimitsExpandWithinDistance? = nil, maxUpTransitions: HierarchyLimitsMaxUpTransitions? = nil) {
        self.expandWithinDistance = expandWithinDistance
        self.maxUpTransitions = maxUpTransitions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expandWithinDistance = "expand_within_distance"
        case maxUpTransitions = "max_up_transitions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(expandWithinDistance, forKey: .expandWithinDistance)
        try container.encodeIfPresent(maxUpTransitions, forKey: .maxUpTransitions)
    }
}
