//
// ServiceLimitsHierarchyLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ServiceLimitsHierarchyLimits: Codable, Hashable {
    public var allowModification: Bool? = false
    public var bidirectionalAstar: ServiceLimitsHierarchyLimitsBidirectionalAstar?
    public var costmatrix: ServiceLimitsHierarchyLimitsCostmatrix?
    public var unidirectionalAstar: ServiceLimitsHierarchyLimitsCostmatrix?

    public init(allowModification: Bool? = false, bidirectionalAstar: ServiceLimitsHierarchyLimitsBidirectionalAstar? = nil, costmatrix: ServiceLimitsHierarchyLimitsCostmatrix? = nil, unidirectionalAstar: ServiceLimitsHierarchyLimitsCostmatrix? = nil) {
        self.allowModification = allowModification
        self.bidirectionalAstar = bidirectionalAstar
        self.costmatrix = costmatrix
        self.unidirectionalAstar = unidirectionalAstar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowModification = "allow_modification"
        case bidirectionalAstar = "bidirectional_astar"
        case costmatrix
        case unidirectionalAstar = "unidirectional_astar"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowModification, forKey: .allowModification)
        try container.encodeIfPresent(bidirectionalAstar, forKey: .bidirectionalAstar)
        try container.encodeIfPresent(costmatrix, forKey: .costmatrix)
        try container.encodeIfPresent(unidirectionalAstar, forKey: .unidirectionalAstar)
    }
}
