//
// ThorBidirectionalAstar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ThorBidirectionalAstar: Codable, Hashable {
    public var alternativeCostExtend: Double? = 1.0
    public var alternativeIterationsDelta: Int? = 100_000
    public var hierarchyLimits: HierarchyLimits?
    public var thresholdDelta: Int? = 420

    public init(alternativeCostExtend: Double? = 1.0, alternativeIterationsDelta: Int? = 100_000, hierarchyLimits: HierarchyLimits? = nil, thresholdDelta: Int? = 420) {
        self.alternativeCostExtend = alternativeCostExtend
        self.alternativeIterationsDelta = alternativeIterationsDelta
        self.hierarchyLimits = hierarchyLimits
        self.thresholdDelta = thresholdDelta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alternativeCostExtend = "alternative_cost_extend"
        case alternativeIterationsDelta = "alternative_iterations_delta"
        case hierarchyLimits = "hierarchy_limits"
        case thresholdDelta = "threshold_delta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alternativeCostExtend, forKey: .alternativeCostExtend)
        try container.encodeIfPresent(alternativeIterationsDelta, forKey: .alternativeIterationsDelta)
        try container.encodeIfPresent(hierarchyLimits, forKey: .hierarchyLimits)
        try container.encodeIfPresent(thresholdDelta, forKey: .thresholdDelta)
    }
}
