//
// ThorUnidirectionalAstar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ThorUnidirectionalAstar: Codable, Hashable {
    public var hierarchyLimits: HierarchyLimits?

    public init(hierarchyLimits: HierarchyLimits? = nil) {
        self.hierarchyLimits = hierarchyLimits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hierarchyLimits = "hierarchy_limits"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hierarchyLimits, forKey: .hierarchyLimits)
    }
}
